---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - пользователь должен иметь возможность зарегистрироваться на сайте как с помощью электронного адреса, так и с помощью учетной записи Google
  - форма регистрации должна содержать следующие поля ввода: имя пользователя, номер телефона, адрес электронной почты, пароль, подтверждение пароля
  - регистрация пользователя не должна осуществляться при хотябы одном незаполненном поле
  - имя пользователя при регистрации должно состоять от 3 до 20 символов
  - при попытке зарегистрировать пользователя с уже существующим именем появлеятся информационное сообщение "пользователь с таким именем уже существует"
  - пароль должен состоять от 6 до 15 латинских символов и содержать одну заглавную букву и одну цифру и один из спецсимволов !*@
  - при несовпадении паролей в полях ввода "пароль" и "подтвердите пароль" появляется информационное сообщение "пароли не совпадают"
  - пользователь может авторизоваться на сайте как по адресу электронной почты, так и по имени пользователя
  - у пользователя есть возможность просматривать историю заказов
  - при нажатии на конкретный заказ появляется информация с номером заказа, составом заказа, общей суммой заказа, способом, временем и адресом доставки, а также способом оплаты
  - на странице заказа, если он еще не исполнен, есть возможность отменить заказ или перенести на другое время и день
  - при переходе в корзину и нажатии кнопки "оформить заказ" появляется форма оформления заказа
  - форма оформления заказа содержит поля: Фамилия и имя получателя, номер телефона для связи, адрес доставки, два способа получения заказа самовывоз либо курьером, способ оплаты: наличными при получении; картой онлайн на сайте
  - при заполении формы оформления заказа происходит валидация всех полей на предмет корректности вводимых данных
  - при заполнении всех полей формы оформления заказа становится активной кнопка "Заказать"
  - при выборе способа оплаты "Картой оналайн на сайте" появляется форма ввода данных банковской карты с полями "номер карты", "срок действия карты", "Фамилия и имя держателя карты", "CVV код"
  - на сайте реализован протокол 3-D Secure для безопасной оплаты
  - на сайте есть возможность отобразать товары по возрастанию цены, по убыванию цены, по рейтингу товара, по популярности товара, по размеру скидки
  - в поле ввода "Цена" нельзя вводить буквы и спецсимволы кроме "." и ","
  - при смене языка интерфейса и последующей перзегрузке страницы, язык интерфейса остается как при последнем выборе
  - при обновалении страницы пользователь должен оставаться на той же странице
